### ISSUE TITLE
The visualizatión of CO2 data plot cero values in app movil 

### ISSUE THREAD

**Issue by arttesano** [kike-canaries/canairio_firmware#110]
**Describe the bug**
The visualizatión of CO2 data plot cero values in app movil 

**To Reproduce**
I made an CaiAirIO Monitor whit an ESP32 whit an MHZ19 sensor in serial conections

![app_cero_plot](https://user-images.githubusercontent.com/898289/124679634-68cc3a80-de8a-11eb-9d72-fed5dac6d008.jpg)

**Comment by hpsaturn** [comment]
Thanks for your feedback, but it happened in which ESP32 board?

**Comment by arttesano** [comment]
ESP32-WROOM-32 ESPRESSIF

**Comment by arttesano** [comment]
![MHZ19_APP_CEL](https://user-images.githubusercontent.com/898289/124752099-08221980-deed-11eb-94df-e2f8333e39ac.png)
apparently the problem is a poor power supply

**Comment by hpsaturn** [comment]
Thanks for your feedback!
