### ISSUE TITLE
Flashing ESP32DEV after flashing with wrong board

### ISSUE THREAD

**Issue by Geelhem** [kike-canaries/canairio_firmware#115]
## Steps to Reproduce

I flashed the device with the wrong board firmware  TTGO_T7 instead of ESP32DevKit  (via platform io on MAC)
I have tried to reflash on top but it does not boot! Do I need to factory reset first if so how?

## Logs
 canairio_firmware % pio run -e ESP32DEVKIT --target upload 

Processing ESP32DEVKIT (platform: espressif32; board: lolin32; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/lolin32.html
PLATFORM: Espressif 32 (3.3.1) > WEMOS LOLIN32
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - tool-mkspiffs 2.230.0 (2.30) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 61 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson> 6.18.3
|-- <ESP8266 Influxdb> 3.8.0
|   |-- <HTTPClient> 1.2
|   |   |-- <WiFi> 1.0
|   |   |-- <WiFiClientSecure> 1.0
|   |   |   |-- <WiFi> 1.0
|-- <esp32FOTA> 0.1.4+sha.d1bbc3f
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|   |-- <ArduinoJson> 6.18.3
|   |-- <HTTPClient> 1.2
|   |   |-- <WiFi> 1.0
|   |   |-- <WiFiClientSecure> 1.0
|   |   |   |-- <WiFi> 1.0
|   |-- <Update> 1.0
|   |-- <WiFi> 1.0
|-- <Adafruit Unified Sensor> 1.1.4
|-- <Adafruit AM2320 sensor library> 1.1.4
|   |-- <Adafruit Unified Sensor> 1.1.4
|   |-- <Wire> 1.0.1
|-- <Adafruit BME280 Library> 2.2.0
|   |-- <Adafruit BusIO> 1.8.3
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|   |-- <SPI> 1.0
|   |-- <Adafruit Unified Sensor> 1.1.4
|-- <Adafruit BME680 Library> 2.0.1
|   |-- <Adafruit BusIO> 1.8.3
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|   |-- <SPI> 1.0
|   |-- <Adafruit Unified Sensor> 1.1.4
|-- <Adafruit BusIO> 1.8.3
|   |-- <Wire> 1.0.1
|   |-- <SPI> 1.0
|-- <Adafruit SHT31 Library> 2.0.0
|   |-- <Adafruit BusIO> 1.8.3
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|-- <AHT10> 1.1.0
|   |-- <Wire> 1.0.1
|-- <DHT_nonblocking> 1.0.0+sha.999fd0d
|-- <sps30> 1.4.11
|   |-- <Wire> 1.0.1
|-- <MH-Z19> 1.5.3
|-- <SparkFun SCD30 Arduino Library> 1.0.13
|   |-- <Wire> 1.0.1
|-- <CM1106 UART> 1.0.0+sha.abada3a
|-- <SparkFun Particle Sensor Panasonic SN-GCJA5> 1.0.1+sha.f261968
|   |-- <Wire> 1.0.1
|-- <SenseAirS8> 0.0.1+sha.a2b8c30
|-- <CanAirIO Air Quality Sensors Library> 0.2.8+sha.ae7ec79
|   |-- <Adafruit Unified Sensor> 1.1.4
|   |-- <Adafruit AM2320 sensor library> 1.1.4
|   |   |-- <Adafruit Unified Sensor> 1.1.4
|   |   |-- <Wire> 1.0.1
|   |-- <sps30> 1.4.11
|   |   |-- <Wire> 1.0.1
|   |-- <Adafruit BME280 Library> 2.2.0
|   |   |-- <Adafruit BusIO> 1.8.3
|   |   |   |-- <Wire> 1.0.1
|   |   |   |-- <SPI> 1.0
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|   |   |-- <Adafruit Unified Sensor> 1.1.4
|   |-- <AHT10> 1.1.0
|   |   |-- <Wire> 1.0.1
|   |-- <Adafruit BusIO> 1.8.3
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|   |-- <Adafruit SHT31 Library> 2.0.0
|   |   |-- <Adafruit BusIO> 1.8.3
|   |   |   |-- <Wire> 1.0.1
|   |   |   |-- <SPI> 1.0
|   |   |-- <Wire> 1.0.1
|   |-- <DHT_nonblocking> 1.0.0+sha.999fd0d
|   |-- <MH-Z19> 1.5.3
|   |-- <SparkFun SCD30 Arduino Library> 1.0.13
|   |   |-- <Wire> 1.0.1
|   |-- <Adafruit BME680 Library> 2.0.1
|   |   |-- <Adafruit BusIO> 1.8.3
|   |   |   |-- <Wire> 1.0.1
|   |   |   |-- <SPI> 1.0
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|   |   |-- <Adafruit Unified Sensor> 1.1.4
|   |-- <SparkFun Particle Sensor Panasonic SN-GCJA5> 1.0.1+sha.f261968
|   |   |-- <Wire> 1.0.1
|   |-- <CM1106 UART> 1.0.0+sha.abada3a
|   |-- <SenseAirS8> 0.0.1+sha.a2b8c30
|-- <U8g2> 2.28.8
|   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|-- <configlib>
|   |-- <ArduinoJson> 6.18.3
|   |-- <Preferences> 1.0
|-- <guilib>
|   |-- <gui-utils-oled>
|   |   |-- <U8g2> 2.28.8
|   |   |   |-- <SPI> 1.0
|   |   |   |-- <Wire> 1.0.1
|-- <watchdoglib>
|-- <ESP32 BLE Arduino> 1.0.1
|-- <canairioota>
|   |-- <ArduinoOTA> 1.0
|   |   |-- <Update> 1.0
|   |   |-- <WiFi> 1.0
|   |   |-- <ESPmDNS> 1.0
|   |   |   |-- <WiFi> 1.0
|   |-- <ESPmDNS> 1.0
|   |   |-- <WiFi> 1.0
|   |-- <WiFi> 1.0
|   |-- <esp32FOTA> 0.1.4+sha.d1bbc3f
|   |   |-- <WiFiClientSecure> 1.0
|   |   |   |-- <WiFi> 1.0
|   |   |-- <ArduinoJson> 6.18.3
|   |   |-- <HTTPClient> 1.2
|   |   |   |-- <WiFi> 1.0
|   |   |   |-- <WiFiClientSecure> 1.0
|   |   |   |   |-- <WiFi> 1.0
|   |   |-- <Update> 1.0
|   |   |-- <WiFi> 1.0
|-- <WiFi> 1.0
Building in release mode
Retrieving maximum program size .pio/build/ESP32DEVKIT/firmware.elf
Checking size .pio/build/ESP32DEVKIT/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  18.7% (used 61320 bytes from 327680 bytes)
Flash: [========= ]  88.8% (used 1746480 bytes from 1966080 bytes)
Configuring upload protocol...
AVAILABLE: esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: /dev/cu.usbserial-0001
Uploading .pio/build/ESP32DEVKIT/firmware.bin
esptool.py v3.1
Serial port /dev/cu.usbserial-0001
Connecting....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 24:0a:c4:ef:59:c8
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 1500000
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x001bafff...
Compressed 17104 bytes to 11191...
Writing at 0x00001000... (100 %)
Wrote 17104 bytes (11191 compressed) at 0x00001000 in 0.4 seconds (effective 315.6 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 129...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (129 compressed) at 0x00008000 in 0.1 seconds (effective 281.6 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 440.1 kbit/s)...
Hash of data verified.
Compressed 1746592 bytes to 1041615...
Writing at 0x00010000... (1 %)
Writing at 0x0001ad29... (3 %)
Writing at 0x000250bc... (4 %)
Writing at 0x00031a87... (6 %)
Writing at 0x00037486... (7 %)
Writing at 0x000425b9... (9 %)
Writing at 0x0005a6bd... (10 %)
Writing at 0x000681cb... (12 %)
Writing at 0x0006deba... (14 %)
Writing at 0x00073c15... (15 %)
Writing at 0x0007a009... (17 %)
Writing at 0x0007fd46... (18 %)
Writing at 0x00085c73... (20 %)
Writing at 0x0008aeb3... (21 %)
Writing at 0x000901b4... (23 %)
Writing at 0x0009564d... (25 %)
Writing at 0x0009abfe... (26 %)
Writing at 0x0009ffaf... (28 %)
Writing at 0x000a76f8... (29 %)
Writing at 0x000aeed7... (31 %)
Writing at 0x000b544d... (32 %)
Writing at 0x000bab30... (34 %)
Writing at 0x000c0b13... (35 %)
Writing at 0x000c762f... (37 %)
Writing at 0x000cda3c... (39 %)
Writing at 0x000d36e5... (40 %)
Writing at 0x000d9440... (42 %)
Writing at 0x000e0761... (43 %)
Writing at 0x000e67ed... (45 %)
Writing at 0x000ec765... (46 %)
Writing at 0x000f26b2... (48 %)
Writing at 0x000f859c... (50 %)
Writing at 0x000feaa1... (51 %)
Writing at 0x00104d3a... (53 %)
Writing at 0x0010a7f9... (54 %)
Writing at 0x0011055a... (56 %)
Writing at 0x001163a9... (57 %)
Writing at 0x0011ca04... (59 %)
Writing at 0x0012279a... (60 %)
Writing at 0x00128475... (62 %)
Writing at 0x0012d7ed... (64 %)
Writing at 0x0013313d... (65 %)
Writing at 0x00138f66... (67 %)
Writing at 0x0013eacc... (68 %)
Writing at 0x00144e92... (70 %)
Writing at 0x0014a9e1... (71 %)
Writing at 0x001508fc... (73 %)
Writing at 0x001569c6... (75 %)
Writing at 0x0015c753... (76 %)
Writing at 0x00162bfa... (78 %)
Writing at 0x00168d7e... (79 %)
Writing at 0x0016e74d... (81 %)
Writing at 0x00174607... (82 %)
Writing at 0x0017a188... (84 %)
Writing at 0x0017ff17... (85 %)
Writing at 0x001859b2... (87 %)
Writing at 0x0018b656... (89 %)
Writing at 0x0019172a... (90 %)
Writing at 0x001982a1... (92 %)
Writing at 0x0019e363... (93 %)
Writing at 0x001a4782... (95 %)
Writing at 0x001aad02... (96 %)
Writing at 0x001b1179... (98 %)
Writing at 0x001b6c68... (100 %)
Wrote 1746592 bytes (1041615 compressed) at 0x00010000 in 15.0 seconds (effective 929.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
========================================================================================== [SUCCESS] Took 26.98 seconds ==========================================================================================

Environment    Status    Duration
-------------  --------  ------------
ESP32DEVKIT    SUCCESS   00:00:26.981

**Comment by hpsaturn** [comment]
Maybe do you have the output log? or why you mentioned that doesn't boot? 

Also try to upload it via binaries files, like this:
https://canair.io/docs/firmware_upload.html#canairio-installer

**Comment by hpsaturn** [comment]
Maybe if you need clear complete settings on the ESP32 board, you can use `esp_tool` command for clear flash memory, or you can use the CanAirIO installer command like this:

```bash
./install.sh erase /dev/ttyUSBX
```
