### ISSUE TITLE
Panasonic SPS not recognised

### ISSUE THREAD

**Issue by Geelhem** [kike-canaries/canairio_firmware#116]
I have just flashed my ESP32DevKit | ESP32DevKit, NodeMCU V3, ** | OLED 128x64 |  with HacksterIO 
using the platform IO method the board boots but one line says detected sensor : FAILED!

I have checked the connections and pin numbers

**Comment by hpsaturn** [comment]
Please first connect your Android Phone to the board via Bluetooth and in settings->mobile statation->select your sensor if you connected it via UART. If you connected it via I2C you don't need select nothing, with `auto` is enough.
