### ISSUE TITLE
Homologate RSSI WiFi Signal to icon like TFT version

### ISSUE THREAD

**Issue by hpsaturn** [kike-canaries/canairio_firmware#173]
**Summary.**

Right now we have the RSSI in the bottom of OLED version, maybe we should change it to WiFi amplitud icon like TFT version

**Comment by danielbernalb** [comment]
The RSSI value in the screen are very useful for fixed stations during the installation. The icon only have 3-4 levels, the number give a detailed info.

**Comment by hpsaturn** [comment]
Yes, but the idea is put the value in number in a `details` section in the future. For now in OLED the number will be there and also via log, but in the future only in the `details` or `info` screen and in the main screen a RSSI icon like a TFT version.
