### ISSUE TITLE
Add sensor Cubic PM1006K

### ISSUE THREAD

**Issue by erguro1973** [kike-canaries/canairio_firmware#177]
Please add PM sensor manufacturer CUBIC Model PM1006k

- Built-in MCU, directly output particle mass concentration (μg/m³)
- Optimized lens design, the sensor can identify 0.3μm particle
- High accuracy, high stability, quick response
- Temperature compensation with the whole measurement range
- Auto lens dust deposition correction
- Compact structure, light weight and easy for installation

Link to datasheet:  [http://www.jdscompany.co.kr/download.asp?gubun=07&filename=PM1006_LED_PARTICLE_SENSOR_MODULE_SPECIFICATIONS.pdf](url)

**Comment by hpsaturn** [comment]
Hi @erguro1973 good news, we finally did it, we released a new version that has support to this sensor:
https://canair.io/docs/canairio_ikea.html

Thanks!

**Comment by erguro1973** [comment]
Great Job!! Congrats for the big efforts
