### ISSUE TITLE
No values

### ISSUE THREAD

**Issue by RIMSKO** [kike-canaries/canairio_firmware#197]
My setup is:
TTGO T-Display
Sensirion SPS30
Sensirion SCD30
On the graf i the app only CO2 shows value PM,Temp and Humidity shows zero

**Comment by roberbike** [comment]
Maybe the correct variables are not selected in the app

**Comment by hpsaturn** [comment]
@roberbike in your setup works fine? maybe with Samsung phone we have a issue, because @RIMSKO reported these issues with this setup but also with a Samsung phone.

**Comment by RIMSKO** [comment]
@roberbike @hpsaturn PM and CO2 shows value RH and TEMP is zero

**Comment by hpsaturn** [comment]
remember that with SCD30 the Temperature and Humidity variables are CO2T and CO2H. Maybe it is the trouble?

**Comment by RIMSKO** [comment]
@hpsaturn That was the problem, Thanks!
