### ISSUE TITLE
ESPPICOD4 RX and TX pins

### ISSUE THREAD

**Issue by roberbike** [kike-canaries/canairio_firmware#203]
The web installer show  : 
![image](https://user-images.githubusercontent.com/20878412/154822105-1b6cd63d-bb5d-4aa4-9f6a-56c355b0f95c.png)

But the sensor lib define this pins in sensors.hpp: 

![image](https://user-images.githubusercontent.com/20878412/154822140-b0f7e35d-1ad3-4d3c-83ca-5c1343d341cd.png)

**Comment by hpsaturn** [comment]
We need a new flavor on the firmware level and added the definitions on sensorslib too.

**Comment by hpsaturn** [comment]
We could close this issue with the last testing version? What do you think?
