### ISSUE TITLE
sds011 shows 0 values. Serial issue.

### ISSUE THREAD

**Issue by roberbike** [kike-canaries/canairio_firmware#214]
Firmware 906.
Board esp32F
Oled
BMP280.
After some hours runing very well, the serial uart (16-17) stops. Testing the SDS011 with direct conection to a Pc, it works.
After a few days with the devices disconnected, they are reconnected and work again for a few hours.
Tested with different boards, same result.

Connected the sensor to an esp82666 board with sensors community firmware, it has been working for days without any error.

This sensor has a command to leave it on standbye. Could this be the issue?

**Comment by hpsaturn** [comment]
This issue right now is fixed, isn't it? Please close if yes.

**Comment by roberbike** [comment]
Power supply was the fault.
