### ISSUE TITLE
M5Stack-Cplus gpio_set_level(226): GPIO output gpio_num error

### ISSUE THREAD

**Issue by markusvankempen** [kike-canaries/canairio_firmware#231]
## Overview
Can not read I2C sensors anymore . ENVIII nor SHT30 etc ...
gpio_set_level(226): GPIO output gpio_num error

## Debug output
E (345486) gpio: GPIO can only be used as input mode
E (345486) gpio: gpio_set_level(226): GPIO output gpio_num error
E (345507) gpio: gpio_set_level(226): GPIO output gpio_num error
E (347537) gpio: gpio_set_level(226): GPIO output gpio_num error
E (347788) gpio: GPIO can only be used as input mode
E (347788) gpio: gpio_set_level(226): GPIO output gpio_num error
E (347809) gpio: gpio_set_level(226): GPIO output gpio_num error

## Device config

== CanAirIO Setup ==

-->[CONF] debug is enable.
-->[HEAP] CONF bytes used	: 0000b/207Kb
E (1029) ledc: freq_hz=0 duty_resolution=13
-->[TGUI] display config ready.
-->[TGUI] disp⸮⸮啑⸮welcome screen
-->[HEAP] GLIB bytes used	: 0996b/206Kb
-->[POWR] CPU Speed: 80 MHz
-->[POWR] == enable sensors ==
-->[INFO] ESP32MAC		: 4C:75:25:C5:85:1A
-->[INFO] Hostname		: CanAirIO51A
-->[INFO] Revision		: r911
-->[INFO] Firmware		: 0.5.5
-->[INFO] Flavor  		: M5STICKCPLUS
-->[INFO] Target  		: dev
-->[INFO] == Detecting Sensors ==
-->[INFO] Sensorslib version	: 0.5.7
-->[INFO] enable sensor GPIO	: 27
-->[HEAP] GPIO bytes used	: 0016b/206Kb
-->[INFO] config UART sensor	: GENERIC
-->[SLIB] new sample time	: 30
-->[SLIB] CanAirIO SensorsLib	: v0.5.7r363
-->[SLIB] sensorslib devmod	: true
-->[SLIB] temperature offset	: 0.00
-->[SLIB] altitude offset   	: 0.00
-->[SLIB] sea level pressure	: 1013.25 hPa
-->[SLIB] only i2c sensors  	: true
-->[SLIB] attempt enable sensor	: SCD30
-->[SLIB] attempt enable sensor	: SPS30
[W][SLIB] SPS30 setup message 	: could not probe. 
-->[SLIB] attempt enable sensor	: GCJA5
-->[SLIB] attempt enable sensor	: SCD4X
[W][SLIB] SCD4x stopping error 	: 267
-->[SLIB] attempt enable sensor	: BME680
-->[SLIB] attempt enable sensor	: BMP280
-->[SLIB] attempt enable sensor	: BME280
-->[SLIB] attempt enable sensor	: AM232X
-->[SLIB] attempt enable sensor	: SHT31
-->[SLIB] attempt enable sensor	: AHT10
-->[SLIB] attempt enable sensor	: DHTX
-->[SLIB] Sensors devices count	: 0 ()
-->[INFO] Main sensors detected	: 0
-->[INFO] registered units	:
-->[SLIB] Preview sensors values	: 
-->[SLIB] Sensors devices count	: 0 ()
-->[SLIB] Sensors units count	: 0 ()
-->[INFO] restored saved unit 	: PM2.5
-->[INFO] not found! set to	: NUNIT
-->[SLIB] Sensors units count	: 0 ()
-->[HEAP] SLIB bytes used	: 1032b/205Kb
-->[WDOG] watchdog check each	: 120 seconds.
-->[HEAP] WDOG bytes used	: 0152b/205Kb
-->[WIFI] connecting to network	: vanishinglake...... done.
-->[WIFI] device network IP	: 10.0.4.122
-->[WIFI] cloud publish interval	: 60 sec.
-->[FOTA] remote OTA update 	: not need update
-->[IFDB] InfluxDB config  	: influxdb.canair.io:8086
-->[IFDB] influxdb.canair.io	: connected!
-->[MQTT] mqtt.anaire.org	: connected!
-->[HEAP] WIFI bytes used	: 39916b/166Kb
-->[INFO] InfluxDb cloud 	: enabled
-->[INFO] WiFi current config	: enabled
-->[BTLE] Bluetooth GATT server	: ready for config client!

**Comment by hpsaturn** [comment]
I think that it is the same issue: 
https://github.com/kike-canaries/canairio_firmware/issues/229

**Comment by markusvankempen** [comment]
@hpsaturn fyi rev910 prod works fine
