### ISSUE TITLE
[Devel] PM2.5 value is not showed in the first case of use

### ISSUE THREAD

**Issue by hpsaturn** [kike-canaries/canairio_firmware#256]
## Overview

In the last devel branch with the PR #255, maybe the new floats support feature when is an integer (i.e PM2.5), is showing a 0000 in the GUI.

**Comment by roberbike** [comment]
Leaving mailValue with previous values, solve the bug.
But when main value is changues pressing right button, the new value is minorValue and has one deccimal

**Comment by hpsaturn** [comment]
I think that I resolved the issue. Please check the last commit.

**Comment by hpsaturn** [comment]
in the last devel version the issue was fixed
