### ISSUE TITLE
CanAirIO with the Panasonic sensor freeze above 1000ug/m3

### ISSUE THREAD

**Issue by danielbernalb** [kike-canaries/canairio_firmware#57]
The new support for the Panasonic have an issue:
This sensor have a broader range: 0μg/m3 – 2,000μg/m3 (UART).
When the measurement is over 999 the sensor don´t show anything, looks like is been freezed.
When returns to a lower value than 1000 is ok.

**Comment by hpsaturn** [comment]
old issue, I think that it is was resolved.
