### ISSUE TITLE
Worldmap Panel for CanAirIO using the database in InfluxDB

### ISSUE THREAD

**Issue by danielbernalb** [kike-canaries/canairio_firmware#63]
status: help wanted
Failed to map Grafana with the current database hosted on the InfluxDB.
In our case we have the nex format
![a1e184bb-0ad4-4ee0-8dce-a1bf744cbc64](https://user-images.githubusercontent.com/42117424/86953837-9e750100-c11a-11ea-9478-66ef83a337bf.jpg)
and Grafana can't seem to read the complete table.
Anyone know how to get the Worldmap plugin to read the database formatted like this?

**Comment by hpsaturn** [comment]
Please clarify the issue with the dataset, what is the reading issue, please add output here maybe?

**Comment by hpsaturn** [comment]
Testing the next query, the current data structure are ok for `Worldmap plugin`:

![screenshot20200708_233941](https://user-images.githubusercontent.com/423856/86974573-df026800-c176-11ea-957c-c320478c2f1b.jpg)

**Comment by danielbernalb** [comment]
> Testing the next query, the current data structure are ok for `Worldmap plugin`:
> 
> ![screenshot20200708_233941](https://user-images.githubusercontent.com/423856/86974573-df026800-c176-11ea-957c-c320478c2f1b.jpg)

Thank you, great job

**Comment by hpsaturn** [comment]
I found the 'alias' workaround in the next thread:

https://community.grafana.com/t/influxdb-and-grafana-plugin-worldmap-panel/16761

**Comment by hpsaturn** [comment]
The last version of CanAirIO have automatic publication to world map in Grafana.
