### ISSUE TITLE
Heltec wifi kit 32 problem between oled and sensirion uart sensor

### ISSUE THREAD

**Issue by roberbike** [kike-canaries/canairio_firmware#88]
Hi, I am encountering a problem with the Heltec wifi kit 32 board, when I select the sensirion sps30 pm sensor, the oled stops working. With the mh-z19 this does not happen. I have select pin 17 and 18 for uart2, because the oled use pin 16 for rst.
I think the sensirion library changes pin 18 to pin 16 and enter in conflicts with the oled.

**Comment by hpsaturn** [comment]
this issue was resolved right? I'm going close for now, please re-opened if not.

**Comment by roberbike** [comment]
My Heltec board is dead. I have one issue with it. "Brownout detector was triggered" , so I can not make test with this board.
